### ISSUE TITLE
De naam van de meester-tak is `master`

### ISSUE THREAD

**Issue by lboekhorst** [matthijsgroen/tekst-avontuur#3]
De naam van deze tak moet `meester` zijn.

**Comment by matthijsgroen** [comment]
Is de hoofd tak niet de stam?

**Comment by lboekhorst** [comment]
`stam` lijkt me prima :+1:

**Comment by matthijsgroen** [comment]
Opgelost!

**Comment by matthijsgroen** [comment]
Ik ga hem toch hernoemen.... Naar `bron`

**Comment by matthijsgroen** [comment]
Helaas, om `gh-pages` niet vanuit een aparte branch te laten komen (te omslachtig met publicatie) moet het uit de `docs/` map komen vanuit de `master` branch .. 😞 dus we gaan terug naar `master`
